#!/bin/bash

pushd /usr/targets/ &> /dev/null
: ${CURRENT_TARGET:=`basename $(readlink -f current)`}
popd &> /dev/null

: ${ROOT:="/usr/targets/${CURRENT_TARGET}/root"}
: ${PORTAGE_CONFIGROOT:=${ROOT}}
: ${PORTAGE_TMPDIR:="/usr/targets/${CURRENT_TARGET}/xbuild"}
EBUILD=`which ebuild 2> /dev/null` || { echo "ebuild not found in ${PATH}"; exit 1; }

[[ -d "${PORTAGE_TMPDIR}" ]] || mkdir -p ${PORTAGE_TMPDIR}
ROOT=${ROOT} PORTAGE_CONFIGROOT=${PORTAGE_CONFIGROOT} PORTAGE_TMPDIR=${PORTAGE_TMPDIR} SCM_WORKDIR="True" ${EBUILD} "$@"
