#!/bin/bash

pushd /usr/targets/ &> /dev/null
: ${CURRENT_TARGET:=`basename $(readlink -f current)`}
popd &> /dev/null

: ${ROOT:="/usr/targets/${CURRENT_TARGET}/root"}
LAYMAN=`which layman 2> /dev/null` || { echo "layman not found in ${PATH}"; exit 1; }

XMLLIST=""
# Create xml list to enable
for xmlfile in ${ROOT}/etc/layman/overlays/*.xml ; do
    XMLLIST="${XMLLIST} -o file://${xmlfile}"
done

${LAYMAN} --config=${ROOT}/etc/xlayman.cfg ${XMLLIST} "$@"
